In [13]:
import numpy as np
x=np.arange(2,33,2).reshape((4,4))
std1=np.std(x)
mean1=np.mean(x)
res=x[(x>mean1-std1/2)&(x<mean1+std1/2)]
print(x)
print(std1)
print(mean1)
print(res)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
9.219544457292887
17.0
[14 16 18 20]
