In [2]:
import numpy as np
n=int(input("enter the number"))
x=np.full((n,n),1)
y=np.array([range(1,n+1)]) 
print(x*y)

enter the number7
[[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]
